// <auto-generated />
using System;
using HomelabBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomelabBot.Data.Migrations
{
    [DbContext(typeof(HomelabDbContext))]
    [Migration("20260208134743_AddAlertEscalations")]
    partial class AddAlertEscalations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("HomelabBot.Data.Entities.AlertEscalation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgementMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PhoneCallInitiatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwilioCallSid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertFingerprint");

                    b.HasIndex("Status");

                    b.ToTable("AlertEscalations");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.ConversationMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.Investigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Resolved");

                    b.HasIndex("ThreadId");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.InvestigationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvestigationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plugin")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.ToTable("InvestigationSteps");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.Knowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("Context")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContradictsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVerified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Topic");

                    b.HasIndex("Topic", "IsValid");

                    b.ToTable("Knowledge");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.LlmInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullMessagesJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("Timestamp");

                    b.ToTable("LlmInteractions");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommonCause")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symptom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symptom");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.ToolCallLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlmInteractionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LlmInteractionId");

                    b.ToTable("ToolCallLogs");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.ConversationMessage", b =>
                {
                    b.HasOne("HomelabBot.Data.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.InvestigationStep", b =>
                {
                    b.HasOne("HomelabBot.Data.Entities.Investigation", "Investigation")
                        .WithMany("Steps")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.LlmInteraction", b =>
                {
                    b.HasOne("HomelabBot.Data.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.ToolCallLog", b =>
                {
                    b.HasOne("HomelabBot.Data.Entities.LlmInteraction", "LlmInteraction")
                        .WithMany("ToolCalls")
                        .HasForeignKey("LlmInteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LlmInteraction");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.Investigation", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("HomelabBot.Data.Entities.LlmInteraction", b =>
                {
                    b.Navigation("ToolCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
